language: node_js
node_js:
  - "6"
  - "6.1"
  - "5.11"
  # - "0.6"
  - "iojs"
install:
  - npm install -g mocha
  - npm install -g istanbul
  - npm install -g codecov
script:
  - istanbul cover mocha --report lcovonly -- -R spec
  - codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)
